parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 3306
    database_name: {DBNAME}
    database_user: {DBUSER}
    database_password: {DBPASS}
    database_path: null
    database_table_prefix: null

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       null
    mailer_password:   null

    locale:            en

    # A secret key that's used to generate certain security-related tokens
    secret:            {DESKEY}

    # two factor stuff
    twofactor_auth: true
    twofactor_sender: no-reply@wallabag.org

    # fosuser stuff
    fosuser_confirmation: true

    from_email: no-reply@wallabag.org
